# Generated by Django 5.2.6 on 2025-09-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'state',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobno', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Delete')], default=1)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.state')),
            ],
            options={
                'db_table': 'family_head',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_dob', models.DateField()),
                ('member_marital', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10)),
                ('member_wedDate', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=10, null=True)),
                ('member_photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Delete')], default=1)),
                ('family_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.familyhead')),
            ],
            options={
                'db_table': 'family_member',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Delete')], default=1)),
                ('family_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='family.familyhead')),
            ],
            options={
                'db_table': 'hobby',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.state'),
        ),
    ]
