# Generated by Django 5.2.6 on 2025-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Delete')], default=1),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='member_marital',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='', max_length=10),
        ),
    ]
