# Generated by Django 5.2.6 on 2025-09-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_city_status_state_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
