# Generated by Django 5.2.6 on 2025-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_familyhead_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
